spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gudinafu/config-repo.git
          username: lideheng6379@163.com
          password: Lide19921123
          basedir: H:\study\mooc\config\basedir

#暴露/bus-refresh接口
management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/
server:
  port: 8400

